-- MySQL Script generated by MySQL Workbench
-- Tue May  8 14:30:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tipo` (
  `Id` INT NOT NULL,

  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Encuesta` (
  `idEncuesta` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Tipo_Id` INT NOT NULL,
  `Fecha` DATE NOT NULL;
  PRIMARY KEY (`idEncuesta`),
  INDEX `fk_Encuesta_Tipo1_idx` (`Tipo_Id` ASC),
  CONSTRAINT `fk_Encuesta_Tipo1`
    FOREIGN KEY (`Tipo_Id`)
    REFERENCES `Tipo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pregunta` (
  `idPregunta` VARCHAR(10) NOT NULL,
  `TipoPregunta` VARCHAR(45) NOT NULL COMMENT 'Aqui se dirá si es abierta, opción múltiple, calificación, etc.',
  `Pregunta` VARCHAR(200) NOT NULL,
  `Respuesta1` VARCHAR(45) NOT NULL,
  `Respuesta2` VARCHAR(45) NULL,
  `Respuesta3` VARCHAR(45) NULL,
  `Respuesta4` VARCHAR(45) NULL,
  `Respuesta5` VARCHAR(45) NULL,
  `NoRespuesta` INT NOT NULL COMMENT 'Dirá cuántas opciones de respuesta habrán',
  `Encuesta_idEncuesta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `fk_Pregunta_Encuesta_idx` (`Encuesta_idEncuesta` ASC),
  CONSTRAINT `fk_Pregunta_Encuesta`
    FOREIGN KEY (`Encuesta_idEncuesta`)
    REFERENCES `Encuesta` (`idEncuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Respuesta` (
  `idRespuesta` VARCHAR(10) NOT NULL,
  `Respuesta` VARCHAR(45) NULL,
  `Encuesta_idEncuesta` VARCHAR(10) NOT NULL,
  `Pregunta_idPregunta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_Respuesta_Encuesta1_idx` (`Encuesta_idEncuesta` ASC),
  INDEX `fk_Respuesta_Pregunta1_idx` (`Pregunta_idPregunta` ASC),
  CONSTRAINT `fk_Respuesta_Encuesta1`
    FOREIGN KEY (`Encuesta_idEncuesta`)
    REFERENCES `Encuesta` (`idEncuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`Pregunta_idPregunta`)
    REFERENCES `Pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
